'@ssen/*':
  version: 2.1.0-alpha.1
  tag: canary
  module: commonjs
rocket-punch:
  version: 2.1.0-alpha.1
  tag: canary
  module: commonjs
  packageJson:
    bin:
      'rocket-punch': ./bin/rocket-punch.js
    keywords:
      - multi package
      - npm
      - package
      - typescript