'@ssen/*':
  version: 1.3.4
  tag: latest
  module: commonjs
rocket-punch:
  version: 1.3.5
  tag: latest
  module: commonjs
  packageJson:
    bin:
      'rocket-punch': ./bin/rocket-punch.js
    keywords:
      - multi package
      - npm
      - package
      - typescript