'@ssen/*':
  version: 1.0.0-alpha.9
  tag: latest
  module: commonjs
rocket-punch:
  version: 1.0.0-alpha.9
  tag: latest
  module: commonjs
  packageJson:
    bin:
      'rocket-punch': ./bin/rocket-punch.js
